/* Generated by TypeSharpV3 dev-version */
declare var $ts_handle_response: (response: Response) => any;
declare var $ts_handle_error: (reason: any) => void;

export namespace ChoccyAdmin.Server {
  export interface WeatherForecast {
    date: Date;
    temperatureC: number;
    temperatureF: number;
    summary?: string | undefined;
  }
}
export namespace ChoccyAdmin.Server.Controllers {
  export class HomeController {
    async index(): Promise<ChoccyAdmin.Server.Controllers.HomeController.AA | undefined> {
      return fetch(`/api/Home`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as ChoccyAdmin.Server.Controllers.HomeController.AA | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
  }
  export class WeatherForecast2Controller {
    async get(): Promise<Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined> {
      return fetch(`/api/WeatherForecast2`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
    async index(): Promise<string | undefined> {
      return fetch(`/api/WeatherForecast2`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as string | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
  }
  export class WeatherForecast3Controller {
    async get(): Promise<Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined> {
      return fetch(`/api/WeatherForecast3`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
    async index(): Promise<string | undefined> {
      return fetch(`/api/WeatherForecast3`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as string | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
  }
  export class WeatherForecast4Controller {
    async get(): Promise<Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined> {
      return fetch(`/api/WeatherForecast4`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
    async index(): Promise<string | undefined> {
      return fetch(`/api/WeatherForecast4`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as string | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
  }
  export class WeatherForecastController {
    async get(): Promise<Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined> {
      return fetch(`/api/WeatherForecast`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as Array<ChoccyAdmin.Server.WeatherForecast | undefined> | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
    async index(): Promise<string | undefined> {
      return fetch(`/api/WeatherForecast`, {
        method: 'GET'
      }).then(async response => {
        if (typeof $ts_handle_response !== 'undefined') {
          return await $ts_handle_response(response) as any;
        }
        return await response.json() as string | undefined;
      }).catch(reason => {
        if (typeof $ts_handle_error !== 'undefined') {
          $ts_handle_error(reason);
        }
        return undefined;
      });
    }
  }
}
export namespace ChoccyAdmin.Server.Controllers.HomeController {
  export interface AA {
    name?: string | undefined;
  }
}